name: "AutoSSH Ping"
version: "0.1.2"
slug: autossh_ping
description: "Wait for a successful ping and automatically connect to a ssh server for forwarding ports"
url: "https://github.com/orgisd/hassio-addons"
arch:
  - armv7
  - armhf
  - amd64
  - aarch64
  - i386
startup: application
boot: auto
init: false
host_network: true
options:
  hostname: ""
  ssh_port: 22
  username: "autossh"
  remote_forwarding: []
  local_forwarding: []
  other_ssh_options: "-v"
  monitor_port: 0
  gatetime: 30
schema:
  hostname: str
  ssh_port: int(1,65535)
  username: str
  remote_forwarding:
    - str
  local_forwarding:
    - str
  other_ssh_options: str
  monitor_port: int(0,65535)
  gatetime: int(1,3600)
